# -*- coding: utf-8 -*-
"""
Created on Thu Jan 17 06:15:16 2019

@author: wwww
"""

s='{"__jsonclass__":["NumericTensor",[{"data":"objref:TUVPVwQAAAAAAAAAAAAAAMAAAAAAAABGXuI/xsXt+UqM4U8qh3bQTwAAAAAABAAAjACPAEaTGgKEQobQVBwJ2MJuAAAAAHsANgAxADIARgA0AEIAOQAyAC0ANwA1AEYARQAtADQAOQA3ADYALQA4ADgAMgBEAC0ARgA1AEQAMwA1ADEAQwBGAEYANQBDADAAfQA6AF8AXwB1AG4AbQBhAHIAcwBoAGEAbABfAF8APQAtADEAMQAxAAAAAABNRU9XAQAAAAAAAAAAAAAAwAAAAAAAAEYAAAAAAAAAAKQHecyN/NOFkcyXdeTr11USGAAALCB4SRBfMb4bEC8PAAAAAA==:","type":"Float64Array","size":[1024,1024,64]}]]}'
s='{"__jsonclass__":["NumericTensor",[{"data":"objref:TUVPVwQAAAAAAAAAAAAAAMAAAAAAAABGXuI/xsXt+UqM4U8qh3bQTwAAAAAABAAAjACPAEaTGgKEQobQVBwJ2MJuAAAAAHsANgAxADIARgA0AEIAOQAyAC0ANwA1AEYARQAtADQAOQA3ADYALQA4ADgAMgBEAC0ARgA1AEQAMwA1ADEAQwBGAEYANQBDADAAfQA6AF8AXwB1AG4AbQBhAHIAcwBoAGEAbABfAF8APQAtADEAMQAxAAAAAABNRU9XAQAAAAAAAAAAAAAAwAAAAAAAAEYAAAAAAAAAAKQHecyN/NOFqMf7zZBUP88U2AAALCB4STuUmSIJ73orAAAAAA==:","type":"Float64Array","size":[1024,1024,256]}]]}'

def eee(a,b):
    return (a,b)